# Generated by Django 5.1.15 on 2026-04-22 14:18
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymetrics",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="bodymetrics",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="bodymetrics",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_by",
                to="db.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to="db.useraccount",
            ),
        ),
    ]
