# Generated by Django 5.1.15 on 2026-04-28 14:23
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_change_audit_fks_to_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary"),
                    ("lightly_active", "Lightly Active"),
                    ("moderately_active", "Moderately Active"),
                    ("very_active", "Very Active"),
                    ("extra_active", "Extra Active"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dietary_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("omnivore", "Omnivore"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("keto", "Keto"),
                    ("mediterranean", "Mediterranean"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fitness_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="food_allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="main_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lose_weight", "Lose Weight"),
                    ("gain_muscle", "Gain Muscle"),
                    ("maintain", "Maintain"),
                    ("improve_fitness", "Improve Fitness"),
                    ("increase_flexibility", "Increase Flexibility"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="meals_per_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="training_days_per_week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="training_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gym", "Gym"),
                    ("home", "Home"),
                    ("outdoor", "Outdoor"),
                    ("mixed", "Mixed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workout_duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diabetes",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("type1", "Type 1"),
                            ("type2", "Type 2"),
                            ("prediabetes", "Prediabetes"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("hypertension", models.BooleanField(default=False)),
                ("heart_condition", models.BooleanField(default=False)),
                ("celiac_disease", models.BooleanField(default=False)),
                ("lactose_intolerance", models.BooleanField(default=False)),
                ("injuries", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("other_conditions", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to="db.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "user_health_profile",
            },
        ),
    ]
