# Generated by Django 5.1.15 on 2026-04-30 14:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_userprofile_activity_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disliked_foods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_foods",
            field=models.TextField(blank=True, null=True),
        ),
    ]
