# Generated by Django 5.1.15 on 2026-05-07 13:53
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_dailyroutine_exercise_routineexercise_trainingplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="egg_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="nut_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="shellfish_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="soy_allergy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="disliked_foods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_foods",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DailyMealPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                ("total_kcal", models.IntegerField(default=0)),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fat_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "daily_meal_plan",
                "ordering": ["day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("goal", models.CharField(max_length=30)),
                ("weeks_duration", models.IntegerField(default=4)),
                ("daily_kcal_target", models.IntegerField()),
                ("daily_protein_g", models.IntegerField()),
                ("daily_carbs_g", models.IntegerField()),
                ("daily_fat_g", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="db.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_plan",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("morning_snack", "Morning Snack"),
                            ("lunch", "Lunch"),
                            ("afternoon_snack", "Afternoon Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "serving_description",
                    models.CharField(default="1 serving", max_length=200),
                ),
                ("kcal", models.IntegerField()),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("carbs_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("fat_g", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_lactose_free", models.BooleanField(default=False)),
                ("is_keto", models.BooleanField(default=False)),
                ("is_mediterranean", models.BooleanField(default=False)),
                ("is_diabetic_friendly", models.BooleanField(default=False)),
                ("contains_nuts", models.BooleanField(default=False)),
                ("contains_eggs", models.BooleanField(default=False)),
                ("contains_shellfish", models.BooleanField(default=False)),
                ("contains_soy", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "recipe",
            },
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("morning_snack", "Morning Snack"),
                            ("lunch", "Lunch"),
                            ("afternoon_snack", "Afternoon Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "serving_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("kcal", models.IntegerField()),
                ("protein_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("carbs_g", models.DecimalField(decimal_places=1, max_digits=6)),
                ("fat_g", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "daily_meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to="db.dailymealplan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_entries",
                        to="db.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "meal_entry",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyNutritionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_number", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_by",
                        to="db.useraccount",
                    ),
                ),
                (
                    "nutrition_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to="db.nutritionplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to="db.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_nutrition_plan",
                "ordering": ["week_number"],
            },
        ),
        migrations.AddField(
            model_name="dailymealplan",
            name="weekly_nutrition_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_meal_plans",
                to="db.weeklynutritionplan",
            ),
        ),
    ]
