# Seed 80 diverse recipes covering all meal types and dietary profiles.
from django.core.management.base import BaseCommand

from better_life_backend.db.models import Recipe

RECIPES = [
    # ── BREAKFASTS ────────────────────────────────────────────────────────────
    {
        "name": "Rolled oats with banana and honey",
        "description": "Classic oatmeal topped with sliced banana and a drizzle of honey.",
        "meal_type": "breakfast",
        "serving_description": "1 bowl (300g)",
        "kcal": 380,
        "protein_g": 10.0,
        "carbs_g": 72.0,
        "fat_g": 5.5,
        "fiber_g": 6.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Greek yogurt with berries and granola",
        "description": "Creamy Greek yogurt layered with mixed berries and crunchy granola.",
        "meal_type": "breakfast",
        "serving_description": "1 bowl (350g)",
        "kcal": 320,
        "protein_g": 18.0,
        "carbs_g": 44.0,
        "fat_g": 7.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Scrambled eggs with whole-grain toast",
        "description": "Fluffy scrambled eggs served with two slices of toasted whole-grain bread.",  # noqa: E501
        "meal_type": "breakfast",
        "serving_description": "2 eggs + 2 slices toast",
        "kcal": 390,
        "protein_g": 22.0,
        "carbs_g": 38.0,
        "fat_g": 14.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Avocado toast with poached egg",
        "description": "Mashed avocado on sourdough toast topped with a poached egg and chili flakes.",  # noqa: E501
        "meal_type": "breakfast",
        "serving_description": "1 slice toast + 1 egg",
        "kcal": 350,
        "protein_g": 14.0,
        "carbs_g": 30.0,
        "fat_g": 19.0,
        "fiber_g": 7.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Protein smoothie with whey, spinach and banana",
        "description": "Blended smoothie with whey protein, spinach, banana and almond milk.",
        "meal_type": "breakfast",
        "serving_description": "1 large glass (400ml)",
        "kcal": 330,
        "protein_g": 28.0,
        "carbs_g": 38.0,
        "fat_g": 5.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Chia seed pudding with mango",
        "description": "Chia seeds soaked in coconut milk overnight, topped with fresh mango.",
        "meal_type": "breakfast",
        "serving_description": "1 jar (300g)",
        "kcal": 290,
        "protein_g": 7.0,
        "carbs_g": 42.0,
        "fat_g": 10.0,
        "fiber_g": 10.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Vegetable omelette",
        "description": "Three-egg omelette filled with peppers, onion, tomato and herbs.",
        "meal_type": "breakfast",
        "serving_description": "1 omelette",
        "kcal": 300,
        "protein_g": 22.0,
        "carbs_g": 8.0,
        "fat_g": 19.0,
        "fiber_g": 2.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Almond butter toast with sliced apple",
        "description": "Whole-grain toast spread with almond butter, topped with thin apple slices and cinnamon.",  # noqa: E501
        "meal_type": "breakfast",
        "serving_description": "2 slices toast",
        "kcal": 360,
        "protein_g": 12.0,
        "carbs_g": 46.0,
        "fat_g": 15.0,
        "fiber_g": 6.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Cottage cheese with pineapple",
        "description": "Low-fat cottage cheese served with fresh pineapple chunks.",
        "meal_type": "breakfast",
        "serving_description": "1 bowl (300g)",
        "kcal": 250,
        "protein_g": 22.0,
        "carbs_g": 28.0,
        "fat_g": 3.0,
        "fiber_g": 1.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Whole-grain pancakes with maple syrup",
        "description": "Fluffy whole-grain pancakes drizzled with pure maple syrup.",
        "meal_type": "breakfast",
        "serving_description": "3 pancakes",
        "kcal": 420,
        "protein_g": 12.0,
        "carbs_g": 70.0,
        "fat_g": 10.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Quinoa breakfast bowl with nuts and honey",
        "description": "Warm quinoa cooked in milk, topped with mixed nuts, honey and cinnamon.",
        "meal_type": "breakfast",
        "serving_description": "1 bowl (300g)",
        "kcal": 400,
        "protein_g": 14.0,
        "carbs_g": 55.0,
        "fat_g": 14.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    # ── MORNING SNACKS ────────────────────────────────────────────────────────
    {
        "name": "Apple with peanut butter",
        "description": "Medium apple with two tablespoons of natural peanut butter.",
        "meal_type": "morning_snack",
        "serving_description": "1 apple + 2 tbsp peanut butter",
        "kcal": 220,
        "protein_g": 6.0,
        "carbs_g": 28.0,
        "fat_g": 10.0,
        "fiber_g": 4.5,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Mixed nuts and dried fruit",
        "description": "A mix of almonds, walnuts, cashews and dried cranberries.",
        "meal_type": "morning_snack",
        "serving_description": "1 handful (40g)",
        "kcal": 200,
        "protein_g": 5.0,
        "carbs_g": 18.0,
        "fat_g": 13.0,
        "fiber_g": 2.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Hummus with carrot sticks",
        "description": "Creamy hummus served with fresh carrot sticks for dipping.",
        "meal_type": "morning_snack",
        "serving_description": "3 tbsp hummus + 1 carrot",
        "kcal": 160,
        "protein_g": 5.0,
        "carbs_g": 18.0,
        "fat_g": 7.0,
        "fiber_g": 5.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Banana and protein bar",
        "description": "A ripe banana paired with a high-protein snack bar.",
        "meal_type": "morning_snack",
        "serving_description": "1 banana + 1 bar",
        "kcal": 250,
        "protein_g": 14.0,
        "carbs_g": 38.0,
        "fat_g": 5.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Rice cakes with avocado",
        "description": "Plain rice cakes topped with mashed avocado and lemon juice.",
        "meal_type": "morning_snack",
        "serving_description": "3 rice cakes",
        "kcal": 180,
        "protein_g": 3.0,
        "carbs_g": 24.0,
        "fat_g": 8.0,
        "fiber_g": 4.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Greek yogurt with honey",
        "description": "Plain Greek yogurt drizzled with raw honey.",
        "meal_type": "morning_snack",
        "serving_description": "1 small pot (150g)",
        "kcal": 170,
        "protein_g": 13.0,
        "carbs_g": 22.0,
        "fat_g": 3.0,
        "fiber_g": 0.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Edamame with sea salt",
        "description": "Steamed edamame pods lightly seasoned with sea salt.",
        "meal_type": "morning_snack",
        "serving_description": "1 cup edamame (155g)",
        "kcal": 190,
        "protein_g": 17.0,
        "carbs_g": 14.0,
        "fat_g": 8.0,
        "fiber_g": 8.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    # ── LUNCHES ───────────────────────────────────────────────────────────────
    {
        "name": "Grilled chicken breast with brown rice and broccoli",
        "description": "Seasoned grilled chicken breast served with brown rice and steamed broccoli.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 plate (450g)",
        "kcal": 490,
        "protein_g": 45.0,
        "carbs_g": 52.0,
        "fat_g": 8.0,
        "fiber_g": 7.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Salmon salad with quinoa and avocado",
        "description": "Baked salmon flakes over quinoa with avocado, cucumber and lemon dressing.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 plate (400g)",
        "kcal": 520,
        "protein_g": 38.0,
        "carbs_g": 32.0,
        "fat_g": 24.0,
        "fiber_g": 8.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Lentil soup with whole-grain bread",
        "description": "Hearty red lentil soup with vegetables, served with a slice of whole-grain bread.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 large bowl + 1 slice bread",
        "kcal": 430,
        "protein_g": 22.0,
        "carbs_g": 68.0,
        "fat_g": 5.0,
        "fiber_g": 14.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Turkey and vegetable wrap",
        "description": "Sliced turkey breast with lettuce, tomato, cucumber and hummus in a whole-wheat wrap.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 large wrap",
        "kcal": 450,
        "protein_g": 32.0,
        "carbs_g": 48.0,
        "fat_g": 11.0,
        "fiber_g": 6.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Chickpea and spinach curry with basmati rice",
        "description": "Aromatic chickpea and spinach curry in a tomato-based sauce served with basmati rice.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 plate (450g)",
        "kcal": 480,
        "protein_g": 18.0,
        "carbs_g": 78.0,
        "fat_g": 10.0,
        "fiber_g": 12.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Tuna salad with mixed greens",
        "description": "Canned tuna mixed with celery, onion and light mayo over a bed of mixed greens.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 large salad",
        "kcal": 330,
        "protein_g": 36.0,
        "carbs_g": 8.0,
        "fat_g": 16.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Pasta with tomato sauce and lean beef",
        "description": "Whole-wheat pasta with a rich tomato and lean ground beef sauce.",
        "meal_type": "lunch",
        "serving_description": "1 plate (400g)",
        "kcal": 530,
        "protein_g": 32.0,
        "carbs_g": 68.0,
        "fat_g": 12.0,
        "fiber_g": 8.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Tofu stir-fry with vegetables and rice",
        "description": "Firm tofu stir-fried with broccoli, peppers and snap peas in a ginger-soy sauce.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 plate (400g)",
        "kcal": 420,
        "protein_g": 20.0,
        "carbs_g": 56.0,
        "fat_g": 12.0,
        "fiber_g": 7.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Greek salad with feta and olives",
        "description": "Tomatoes, cucumber, red onion, olives and feta cheese with olive oil dressing.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 large salad",
        "kcal": 310,
        "protein_g": 10.0,
        "carbs_g": 14.0,
        "fat_g": 24.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Black bean burrito bowl",
        "description": "Brown rice, black beans, grilled corn, salsa, guacamole and light sour cream.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 bowl (500g)",
        "kcal": 500,
        "protein_g": 20.0,
        "carbs_g": 72.0,
        "fat_g": 14.0,
        "fiber_g": 16.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Grilled sea bass with roasted vegetables",
        "description": "Sea bass fillet grilled with herbs, served with roasted zucchini, peppers and cherry tomatoes.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 fillet + vegetables (380g)",
        "kcal": 370,
        "protein_g": 38.0,
        "carbs_g": 18.0,
        "fat_g": 15.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Egg fried rice with vegetables",
        "description": "Wok-fried rice with scrambled eggs, peas, carrots and spring onions.",
        "meal_type": "lunch",
        "serving_description": "1 plate (400g)",
        "kcal": 450,
        "protein_g": 16.0,
        "carbs_g": 68.0,
        "fat_g": 12.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Caprese salad with mozzarella",
        "description": "Fresh tomatoes, buffalo mozzarella and basil drizzled with olive oil and balsamic glaze.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 plate (300g)",
        "kcal": 300,
        "protein_g": 16.0,
        "carbs_g": 10.0,
        "fat_g": 22.0,
        "fiber_g": 2.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Cauliflower rice bowl with grilled shrimp",
        "description": "Cauliflower rice topped with grilled shrimp, avocado and pico de gallo.",
        "meal_type": "lunch",
        "serving_description": "1 bowl (400g)",
        "kcal": 340,
        "protein_g": 30.0,
        "carbs_g": 18.0,
        "fat_g": 16.0,
        "fiber_g": 8.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": True,
        "contains_soy": False,
    },
    {
        "name": "Minestrone soup with parmesan",
        "description": "Italian vegetable soup with pasta, beans and a sprinkle of parmesan.",
        "meal_type": "lunch",
        "serving_description": "1 large bowl (450g)",
        "kcal": 380,
        "protein_g": 16.0,
        "carbs_g": 60.0,
        "fat_g": 8.0,
        "fiber_g": 12.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Chicken Caesar salad",
        "description": "Grilled chicken strips over romaine lettuce with Caesar dressing and croutons.",  # noqa: E501
        "meal_type": "lunch",
        "serving_description": "1 large salad",
        "kcal": 420,
        "protein_g": 38.0,
        "carbs_g": 18.0,
        "fat_g": 22.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    # ── AFTERNOON SNACKS ──────────────────────────────────────────────────────
    {
        "name": "Orange and almonds",
        "description": "A fresh orange with a small handful of almonds.",
        "meal_type": "afternoon_snack",
        "serving_description": "1 orange + 20g almonds",
        "kcal": 190,
        "protein_g": 5.0,
        "carbs_g": 24.0,
        "fat_g": 9.0,
        "fiber_g": 5.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Celery sticks with cream cheese",
        "description": "Crisp celery sticks stuffed with light cream cheese.",
        "meal_type": "afternoon_snack",
        "serving_description": "4 celery sticks",
        "kcal": 150,
        "protein_g": 5.0,
        "carbs_g": 6.0,
        "fat_g": 11.0,
        "fiber_g": 2.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": True,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Dark chocolate and walnuts",
        "description": "A square of 70%+ dark chocolate with a few walnuts.",
        "meal_type": "afternoon_snack",
        "serving_description": "20g chocolate + 15g walnuts",
        "kcal": 195,
        "protein_g": 4.0,
        "carbs_g": 12.0,
        "fat_g": 15.0,
        "fiber_g": 2.5,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Protein shake with milk",
        "description": "Whey protein powder blended with semi-skimmed milk.",
        "meal_type": "afternoon_snack",
        "serving_description": "1 shaker (300ml)",
        "kcal": 220,
        "protein_g": 26.0,
        "carbs_g": 18.0,
        "fat_g": 4.0,
        "fiber_g": 0.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Sliced cucumber with tzatziki",
        "description": "Fresh cucumber slices with homemade tzatziki dip.",
        "meal_type": "afternoon_snack",
        "serving_description": "1 cup cucumber + 4 tbsp tzatziki",
        "kcal": 130,
        "protein_g": 5.0,
        "carbs_g": 10.0,
        "fat_g": 7.0,
        "fiber_g": 1.5,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Pear with gouda cheese",
        "description": "Sliced pear paired with slices of aged gouda cheese.",
        "meal_type": "afternoon_snack",
        "serving_description": "1 pear + 30g gouda",
        "kcal": 200,
        "protein_g": 8.0,
        "carbs_g": 24.0,
        "fat_g": 8.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Soy yogurt with flaxseeds",
        "description": "Plain soy yogurt topped with ground flaxseeds and a few blueberries.",
        "meal_type": "afternoon_snack",
        "serving_description": "1 small pot (150g)",
        "kcal": 155,
        "protein_g": 8.0,
        "carbs_g": 16.0,
        "fat_g": 6.0,
        "fiber_g": 3.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    # ── DINNERS ───────────────────────────────────────────────────────────────
    {
        "name": "Baked salmon with asparagus",
        "description": "Oven-baked salmon fillet with garlic asparagus and lemon.",
        "meal_type": "dinner",
        "serving_description": "1 fillet + asparagus (380g)",
        "kcal": 420,
        "protein_g": 40.0,
        "carbs_g": 8.0,
        "fat_g": 25.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Chicken thighs with sweet potato mash",
        "description": "Roasted chicken thighs served with creamy sweet potato mash and green beans.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (450g)",
        "kcal": 510,
        "protein_g": 38.0,
        "carbs_g": 42.0,
        "fat_g": 18.0,
        "fiber_g": 7.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Beef stir-fry with broccoli and noodles",
        "description": "Lean beef strips stir-fried with broccoli and mushrooms over egg noodles.",
        "meal_type": "dinner",
        "serving_description": "1 plate (400g)",
        "kcal": 540,
        "protein_g": 36.0,
        "carbs_g": 58.0,
        "fat_g": 16.0,
        "fiber_g": 6.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Vegetable ratatouille with polenta",
        "description": "Classic French ratatouille with zucchini, eggplant and peppers over creamy polenta.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (450g)",
        "kcal": 380,
        "protein_g": 10.0,
        "carbs_g": 62.0,
        "fat_g": 10.0,
        "fiber_g": 10.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Pork tenderloin with roasted root vegetables",
        "description": "Herb-crusted pork tenderloin with roasted carrots, parsnips and red onion.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (430g)",
        "kcal": 460,
        "protein_g": 40.0,
        "carbs_g": 32.0,
        "fat_g": 16.0,
        "fiber_g": 7.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Spaghetti aglio e olio with prawns",
        "description": "Whole-wheat spaghetti with olive oil, garlic, chili flakes and jumbo prawns.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (380g)",
        "kcal": 490,
        "protein_g": 28.0,
        "carbs_g": 64.0,
        "fat_g": 14.0,
        "fiber_g": 7.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": True,
        "contains_soy": False,
    },
    {
        "name": "Stuffed peppers with ground turkey and quinoa",
        "description": "Bell peppers filled with ground turkey, quinoa, tomato sauce and herbs.",
        "meal_type": "dinner",
        "serving_description": "2 stuffed peppers (420g)",
        "kcal": 470,
        "protein_g": 38.0,
        "carbs_g": 42.0,
        "fat_g": 14.0,
        "fiber_g": 8.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Vegan Buddha bowl",
        "description": "Brown rice, roasted chickpeas, kale, red cabbage, avocado and tahini dressing.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 bowl (500g)",
        "kcal": 490,
        "protein_g": 18.0,
        "carbs_g": 62.0,
        "fat_g": 20.0,
        "fiber_g": 14.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Cod fillet with tomato and olive tapenade",
        "description": "Pan-seared cod on a bed of cherry tomatoes, olives and capers.",
        "meal_type": "dinner",
        "serving_description": "1 fillet + vegetables (360g)",
        "kcal": 350,
        "protein_g": 36.0,
        "carbs_g": 12.0,
        "fat_g": 16.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Mushroom and spinach risotto",
        "description": "Creamy Arborio rice with mixed mushrooms, spinach, white wine and parmesan.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (380g)",
        "kcal": 480,
        "protein_g": 14.0,
        "carbs_g": 70.0,
        "fat_g": 14.0,
        "fiber_g": 5.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Lamb chops with roasted garlic and spinach",
        "description": "Grilled lamb chops with roasted whole garlic cloves and sautéed spinach.",
        "meal_type": "dinner",
        "serving_description": "2 chops + side (380g)",
        "kcal": 480,
        "protein_g": 42.0,
        "carbs_g": 8.0,
        "fat_g": 30.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Veggie burger with sweet potato fries",
        "description": "Black bean and quinoa burger patty with lettuce, tomato and sweet potato fries.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 burger + fries (400g)",
        "kcal": 520,
        "protein_g": 18.0,
        "carbs_g": 72.0,
        "fat_g": 16.0,
        "fiber_g": 12.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Baked cod with chickpea stew",
        "description": "Baked cod on top of a hearty chickpea, tomato and paprika stew.",
        "meal_type": "dinner",
        "serving_description": "1 plate (450g)",
        "kcal": 440,
        "protein_g": 38.0,
        "carbs_g": 44.0,
        "fat_g": 10.0,
        "fiber_g": 10.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Tempeh and kale bowl with miso dressing",
        "description": "Pan-seared tempeh over steamed kale and brown rice with a miso-ginger dressing.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 bowl (430g)",
        "kcal": 470,
        "protein_g": 28.0,
        "carbs_g": 52.0,
        "fat_g": 16.0,
        "fiber_g": 9.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Turkey meatballs with zucchini noodles",
        "description": "Lean turkey meatballs in tomato sauce over spiralized zucchini.",
        "meal_type": "dinner",
        "serving_description": "1 plate (400g)",
        "kcal": 380,
        "protein_g": 36.0,
        "carbs_g": 18.0,
        "fat_g": 18.0,
        "fiber_g": 6.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Red lentil dahl with brown rice",
        "description": "Aromatic red lentil dahl with ginger, turmeric and coconut milk, served with rice.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (450g)",
        "kcal": 460,
        "protein_g": 22.0,
        "carbs_g": 70.0,
        "fat_g": 10.0,
        "fiber_g": 14.0,
        "is_vegan": True,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Shrimp tacos with coleslaw",
        "description": "Grilled shrimp in corn tortillas with shredded cabbage slaw and lime crema.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "3 tacos (350g)",
        "kcal": 420,
        "protein_g": 28.0,
        "carbs_g": 48.0,
        "fat_g": 12.0,
        "fiber_g": 6.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": True,
        "contains_soy": False,
    },
    {
        "name": "Beef and vegetable skewers with couscous",
        "description": "Marinated beef and vegetable skewers served with herb couscous.",
        "meal_type": "dinner",
        "serving_description": "2 skewers + couscous (400g)",
        "kcal": 500,
        "protein_g": 36.0,
        "carbs_g": 48.0,
        "fat_g": 16.0,
        "fiber_g": 6.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": False,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Miso salmon with bok choy",
        "description": "Miso-glazed salmon fillet with steamed bok choy and sesame rice.",
        "meal_type": "dinner",
        "serving_description": "1 plate (420g)",
        "kcal": 490,
        "protein_g": 38.0,
        "carbs_g": 40.0,
        "fat_g": 18.0,
        "fiber_g": 4.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": False,
        "is_lactose_free": True,
        "is_keto": False,
        "is_mediterranean": False,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": True,
    },
    {
        "name": "Chickpea fritters with tzatziki",
        "description": "Pan-fried chickpea fritters with fresh herbs, served with tzatziki dip.",
        "meal_type": "dinner",
        "serving_description": "4 fritters + dip (350g)",
        "kcal": 400,
        "protein_g": 18.0,
        "carbs_g": 50.0,
        "fat_g": 14.0,
        "fiber_g": 10.0,
        "is_vegan": False,
        "is_vegetarian": True,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": False,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": False,
        "contains_eggs": True,
        "contains_shellfish": False,
        "contains_soy": False,
    },
    {
        "name": "Pesto chicken with roasted cherry tomatoes",
        "description": "Chicken breast coated in basil pesto, roasted with cherry tomatoes and pine nuts.",  # noqa: E501
        "meal_type": "dinner",
        "serving_description": "1 plate (380g)",
        "kcal": 460,
        "protein_g": 40.0,
        "carbs_g": 10.0,
        "fat_g": 28.0,
        "fiber_g": 3.0,
        "is_vegan": False,
        "is_vegetarian": False,
        "is_gluten_free": True,
        "is_lactose_free": False,
        "is_keto": True,
        "is_mediterranean": True,
        "is_diabetic_friendly": True,
        "contains_nuts": True,
        "contains_eggs": False,
        "contains_shellfish": False,
        "contains_soy": False,
    },
]


class Command(BaseCommand):
    help = "Seed the database with recipe data."

    def handle(self, *args, **options):
        created_count = 0
        for data in RECIPES:
            _, was_created = Recipe.objects.get_or_create(
                name=data["name"], defaults=data
            )
            if was_created:
                created_count += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created_count} new recipes ({len(RECIPES)} total processed)."
            )
        )
