from django.core.management.base import BaseCommand

from better_life_backend.db.models import Exercise

EXERCISES = [
    # ── CHEST ──────────────────────────────────────────────────────────────────
    {
        "name": "Push-ups",
        "description": "Classic push-up from the floor.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Wide Push-ups",
        "description": "Push-ups with hands wider than shoulder-width.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Diamond Push-ups",
        "description": "Push-ups with hands forming a diamond, targeting triceps and inner chest.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Decline Push-ups",
        "description": "Push-ups with feet elevated on a chair to target upper chest.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Clap Push-ups",
        "description": "Explosive push-ups: push hard enough to clap between reps.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 90,
        "difficulty": "advanced",
        "equipment": "none",
    },
    {
        "name": "Dumbbell Press",
        "description": "Lie on a bench and press dumbbells upward.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 90,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Dumbbell Fly",
        "description": "Lie on a bench, open arms wide and bring them together over chest.",
        "muscle_group": "chest",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "dumbbells",
    },
    # ── BACK ───────────────────────────────────────────────────────────────────
    {
        "name": "Superman",
        "description": "Lie face down and lift arms and legs simultaneously.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Reverse Snow Angels",
        "description": "Lie face down and move arms in an arc like snow angels.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Inverted Rows",
        "description": "Lie under a table, grip the edge and pull chest up.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Pull-ups",
        "description": "Overhand grip pull-ups on a bar.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 90,
        "difficulty": "intermediate",
        "equipment": "pull_up_bar",
    },
    {
        "name": "Chin-ups",
        "description": "Underhand grip pull-ups to emphasize biceps.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 90,
        "difficulty": "intermediate",
        "equipment": "pull_up_bar",
    },
    {
        "name": "Dumbbell Row",
        "description": "Brace one knee on a bench and row dumbbell to hip.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Renegade Rows",
        "description": "In push-up position, row one dumbbell at a time.",
        "muscle_group": "back",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 90,
        "difficulty": "advanced",
        "equipment": "dumbbells",
    },
    # ── SHOULDERS ──────────────────────────────────────────────────────────────
    {
        "name": "Pike Push-ups",
        "description": "In a downward-dog position, lower head toward floor.",
        "muscle_group": "shoulders",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Shoulder Taps",
        "description": "In high plank, tap each shoulder alternately.",
        "muscle_group": "shoulders",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Wall Handstand Hold",
        "description": "Kick into a handstand against a wall and hold.",
        "muscle_group": "shoulders",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 20,
        "rest_seconds": 90,
        "difficulty": "advanced",
        "equipment": "none",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "Press dumbbells overhead from shoulder height.",
        "muscle_group": "shoulders",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Lateral Raises",
        "description": "Raise dumbbells to the sides until arms are parallel to floor.",
        "muscle_group": "shoulders",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Front Raises",
        "description": "Raise dumbbells forward to shoulder height.",
        "muscle_group": "shoulders",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    # ── ARMS ───────────────────────────────────────────────────────────────────
    {
        "name": "Tricep Dips",
        "description": "Dip down using hands on a chair or bench behind you.",
        "muscle_group": "arms",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Bicep Curls",
        "description": "Stand and curl dumbbells toward shoulders.",
        "muscle_group": "arms",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Hammer Curls",
        "description": "Neutral-grip curls to work brachialis.",
        "muscle_group": "arms",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Tricep Kickbacks",
        "description": "Hinge forward and extend arm behind you.",
        "muscle_group": "arms",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    {
        "name": "Concentration Curls",
        "description": "Seated curl with elbow braced on inner thigh.",
        "muscle_group": "arms",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "dumbbells",
    },
    # ── LEGS ───────────────────────────────────────────────────────────────────
    {
        "name": "Squats",
        "description": "Feet shoulder-width, lower until thighs are parallel.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 15,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Lunges",
        "description": "Step forward and lower back knee toward floor, alternate legs.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Glute Bridges",
        "description": "Lie on back, feet flat, push hips to ceiling.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 15,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Wall Sit",
        "description": "Slide down a wall until thighs are parallel and hold.",
        "muscle_group": "legs",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Calf Raises",
        "description": "Rise onto toes and lower slowly.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Step-ups",
        "description": "Step up onto a box or stair, alternate legs.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Jump Squats",
        "description": "Squat then explode upward and land softly.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Bulgarian Split Squats",
        "description": "Rear foot elevated on a bench, lower front knee.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 90,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Single-leg Glute Bridge",
        "description": "Glute bridge with one leg extended.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Pistol Squats",
        "description": "Single-leg squat to full depth.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 6,
        "rest_seconds": 90,
        "difficulty": "advanced",
        "equipment": "none",
    },
    {
        "name": "Goblet Squats",
        "description": "Hold a dumbbell at chest height and squat deep.",
        "muscle_group": "legs",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "dumbbells",
    },
    # ── CORE ───────────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "description": "Hold a straight-arm or forearm plank.",
        "muscle_group": "core",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Crunches",
        "description": "Lift shoulders off the floor contracting the abs.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Bicycle Crunches",
        "description": "Alternate elbow-to-knee in a pedalling motion.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Leg Raises",
        "description": "Lie flat and raise straight legs to 90 degrees.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 15,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Russian Twists",
        "description": "Seated, lean back slightly and rotate torso side to side.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Dead Bug",
        "description": "Opposite arm and leg extend slowly while lower back stays flat.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Mountain Climbers",
        "description": "In plank, drive knees alternately toward chest at speed.",
        "muscle_group": "core",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Side Plank",
        "description": "Balance on one forearm and the side of one foot.",
        "muscle_group": "core",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 20,
        "rest_seconds": 45,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "V-ups",
        "description": "Simultaneously raise legs and torso, reaching hands to feet.",
        "muscle_group": "core",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 12,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Hollow Body Hold",
        "description": "Lie flat, press lower back down and hold arms and legs off floor.",
        "muscle_group": "core",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 20,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    # ── CARDIO ─────────────────────────────────────────────────────────────────
    {
        "name": "Jumping Jacks",
        "description": "Jump feet apart while raising arms overhead, then reverse.",
        "muscle_group": "cardio",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 30,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "High Knees",
        "description": "Run in place, bringing knees to hip height.",
        "muscle_group": "cardio",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 30,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Lateral Jumps",
        "description": "Jump side to side over an imaginary line.",
        "muscle_group": "cardio",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 20,
        "rest_seconds": 45,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Burpees",
        "description": "Squat, jump feet back to plank, push-up optional, jump up.",
        "muscle_group": "cardio",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Box Jumps",
        "description": "Jump onto a box or step and step back down.",
        "muscle_group": "cardio",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 60,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Sprints",
        "description": "All-out sprint for 20 seconds.",
        "muscle_group": "cardio",
        "exercise_type": "time",
        "default_sets": 5,
        "default_duration_seconds": 20,
        "rest_seconds": 40,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Jump Rope",
        "description": "Skip rope at a steady pace.",
        "muscle_group": "cardio",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 60,
        "rest_seconds": 30,
        "difficulty": "beginner",
        "equipment": "none",
    },
    # ── FULL BODY ──────────────────────────────────────────────────────────────
    {
        "name": "Inchworm",
        "description": "Hinge at hips, walk hands out to plank and back.",
        "muscle_group": "full_body",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Bear Crawls",
        "description": "Crawl forward and backward on hands and feet.",
        "muscle_group": "full_body",
        "exercise_type": "time",
        "default_sets": 3,
        "default_duration_seconds": 30,
        "rest_seconds": 60,
        "difficulty": "beginner",
        "equipment": "none",
    },
    {
        "name": "Burpee with Push-up",
        "description": "Full burpee adding a push-up at the bottom.",
        "muscle_group": "full_body",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 8,
        "rest_seconds": 90,
        "difficulty": "intermediate",
        "equipment": "none",
    },
    {
        "name": "Turkish Get-up",
        "description": "From lying to standing holding a weight overhead.",
        "muscle_group": "full_body",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 5,
        "rest_seconds": 90,
        "difficulty": "advanced",
        "equipment": "dumbbells",
    },
    {
        "name": "Dumbbell Thruster",
        "description": "Front squat into overhead press in one fluid movement.",
        "muscle_group": "full_body",
        "exercise_type": "reps",
        "default_sets": 3,
        "default_reps": 10,
        "rest_seconds": 90,
        "difficulty": "intermediate",
        "equipment": "dumbbells",
    },
]


class Command(BaseCommand):
    help = "Seed the database with exercise data"

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for data in EXERCISES:
            _, was_created = Exercise.objects.get_or_create(
                name=data["name"],
                defaults=data,
            )
            if was_created:
                created += 1
            else:
                skipped += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Done — {created} exercises created, {skipped} already existed."
            )
        )
